In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
file_path = ('/content/nykaa_campaign_data.csv')
data = pd.read_csv (file_path)
print(data.head())

   Campaign_ID Campaign_Type        Target_Audience  Duration  \
0  NY-CMP-1000  Social Media       College Students        21
1  NY-CMP-1001      Paid Ads  Tier 2 City Customers        18
2  NY-CMP-1002    Influencer                  Youth        23
3  NY-CMP-1003         Email          Working Women        18
4  NY-CMP-1004      Paid Ads       College Students        10

                   Channel_Used  Impressions  Clicks  Leads  Conversions  \
0             WhatsApp, YouTube        57804    6156   3616         2355
1                       YouTube        91801    3321   1971         1357
2     WhatsApp, Google, YouTube        15536    2182    952          755
3  YouTube, Facebook, Instagram        88114    8413   2231          947
4           Facebook, Instagram        96871    3743   2060         1258

   Revenue  Acquisition_Cost   ROI Language  Engagement_Score  \
0  1867515            111.03  6.14    Hindi             20.98
1  1046247            180.83  3.26    Hindi              7.24
2   197055             90.60  1.88  English             25.03
3   376906            249.07  0.60    Hindi             13.15
4   518296            228.60  0.80    Hindi              7.29

        Customer_Segment        Date
0       College Students  29-04-2025
1       College Students  06-04-2025
2       College Students  14-01-2025
3       College Students  04-06-2025
4  Tier 2 City Customers  29-12-2024

In [3]:
data.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [ ]:
data.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,55555.000000,55555.000000,55555.000000,55555.000000,55555.000000,5.555500e+04,55555.000000,55555.000000,55555.000000
mean,17.446044,55087.885357,4688.070507,1877.271119,1032.866925,5.158197e+05,377.347068,2.713807,13.784169
std,7.520438,25930.001514,3178.686285,1435.636117,862.496788,4.900121e+05,541.084524,4.493380,6.353125
min,5.000000,10001.000000,202.000000,56.000000,19.000000,6.183000e+03,9.080000,-0.970000,2.600000
25%,11.000000,32680.000000,2110.000000,779.000000,400.000000,1.777060e+05,105.435000,0.040000,8.360000
50%,17.000000,55182.000000,3907.000000,1481.000000,779.000000,3.604360e+05,207.510000,1.240000,13.600000
75%,24.000000,77514.500000,6688.000000,2605.000000,1414.000000,6.874225e+05,428.580000,3.630000,18.855000
max,30.000000,100000.000000,14868.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,74.420000,30.910000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
dtypes: float64(3), int64(6), object(7)
memory usage: 6.8+ MB

In [ ]:
data.isnull().sum()

Campaign_ID         0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Impressions         0
Clicks              0
Leads               0
Conversions         0
Revenue             0
Acquisition_Cost    0
ROI                 0
Language            0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data["Date"] = pd.to_datetime(data["Date"])

/tmp/ipykernel_1055/2487158108.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data["Date"] = pd.to_datetime(data["Date"])

In [ ]:
"Date"

'Date'

##KPI CREATIONS

CTR

In [ ]:
data["CTR"] = (data["Clicks"] / data["Impressions"]) * 100
print (data["CTR"])

0        10.649782
1         3.617608
2        14.044799
3         9.547858
4         3.863901
           ...
55550    12.399729
55551    13.590635
55552    14.827166
55553     7.509693
55554    12.784699
Name: CTR, Length: 55555, dtype: float64

CONVERATION RATE

In [ ]:
data["Conversion_Rate"] = (data["Conversions"] / data["Clicks"]) * 100
print (data["Conversion_Rate"])

0        38.255361
1        40.861186
2        34.601283
3        11.256389
4        33.609404
           ...
55550    16.601715
55551    27.079408
55552    25.872499
55553    11.874504
55554    36.048725
Name: Conversion_Rate, Length: 55555, dtype: float64

AD SPEND

In [ ]:
data["Ad_Spend"] = data["Acquisition_Cost"] * data["Conversions"]
print (data["Ad_Spend"])

0        261475.65
1        245386.31
2         68403.00
3        235869.29
4        287578.80
           ...
55550    239561.10
55551     56718.28
55552     93708.24
55553     68031.47
55554     66498.34
Name: Ad_Spend, Length: 55555, dtype: float64

CPC

In [ ]:
data["CPC"] = data["Ad_Spend"] / data["Clicks"]
print (data["CPC"])

0        42.474927
1        73.889283
2        31.348763
3        28.036288
4        76.831098
           ...
55550    62.239829
55551    15.267370
55552    14.535170
55553    27.018058
55554    12.656707
Name: CPC, Length: 55555, dtype: float64

CPL

In [ ]:
data["CPL"] = data["Ad_Spend"] / data["Leads"]
print (data["CPL"])

0         72.310744
1        124.498382
2         71.851891
3        105.723572
4        139.601359
            ...
55550    236.720455
55551     25.969908
55552     24.982202
55553    116.492243
55554     25.874840
Name: CPL, Length: 55555, dtype: float64

In [ ]:
data.groupby(data["Date"].dt.month)["Revenue"].sum()

Date
1     2521812438
2     2333105678
3     2570717938
4     2439364737
5     2572782370
6      906477811
7     2630226313
8     2597876736
9     2390680030
10    2583203421
11    2523763004
12    2586353806
Name: Revenue, dtype: int64

In [ ]:
data.groupby(data["Date"].dt.year)["Clicks"].sum()

Date
2024    139148651
2025    121297106
Name: Clicks, dtype: int64

In [ ]:
data["Day"] = data["Date"].dt.day_name()
print(data["Day"])

0          Tuesday
1           Sunday
2          Tuesday
3        Wednesday
4           Sunday
           ...
55550       Sunday
55551       Monday
55552     Thursday
55553     Thursday
55554       Friday
Name: Day, Length: 55555, dtype: object

In [4]:
data.to_csv("nykaa_campaign_cleaned.csv", index=False)